before_script:
 - apt-get install graphicsmagick apache2 libapache2-mod-php7.0 composer php7.0-xml php7.0-cli php7.0-mbstring ghostscript unzip git libreoffice
 - wget https://shopwarelabs.github.io/psh/psh.phar

after_script:
 - php psh.phar clear

stages:
 - build
 - test

build:
 stage: build
 script:
  - php psh.phar build

test:
 stage: test
 script:
  - php psh.phar build
  - php psh.phar test