image: dockerregistry.metaways.net/tine20/documentpreview/build

stages:
 - build
 - test
 - deploy

cache:
 key: ${CI_PIPELINE_ID}
 paths:
  - ./build
  - documentPreviewService-2.1.${CI_PIPELINE_ID}.deb

build_branch:
 stage: build
 only:
  - branches
 script:
  - php psh.phar git-branches:build

test:
 stage: test
 script:
  - php psh.phar git:test

deploy_to_repo:
 stage: deploy
 only:
  - master
 script:
  - php psh.phar git-branches:deploytorepo
 rules:
  - if: $PUSH_TO_REPO == "false"
    when: never
  - when: on_success
 