stages:
 - build
 - test

build:
 stage: build
 cache:
  key: build
  path:
   - build
 script:
  - php psh.phar build

test:
 stage: test
 cache:
  key: build
  path:
   - build
  policy: pull
 script:
  - php psh.phar test