stages:
 - build
 - test
 - deploy
 - clean
 
cache:
 key: build
 paths:
  - build
  - documentPreview.tar.gz

build:
 stage: build
 script:
  - php psh.phar build

test:
 stage: test
 script:
  - php psh.phar test
  
deploy:
 stage: deploy
 artifacts:
  paths:
   - documentPreview-$CI_COMMIT_REF_NAME.tar.gz
 script:
 - echo 1
  
clean:
 stage: clean
 script:
  - php psh.phar clear
  