image: dockerregistry.metaways.net/tine20/documentpreview/build

stages:
 - build
 - test
 - deploy

cache:
 untracked: true

build_branch:
 stage: build
 only:
  - branches
 script:
  - php psh.phar git-branches:build

test:
 stage: test
 script:
  - touch 1
  - ls
  - php psh.phar git:test

deploy_to_repo:
 stage: deploy
 only:
  - master
 script:
  - ls
  - php psh.phar git-branches:deploytorepo
