stages:
 - build
 - test
 - deploy
 - clean
 
cache:
 key: build
 paths:
  - build

build:
 stage: build
 script:
  - php psh.phar build

test:
 stage: test
 script:
  - php psh.phar test
  
deploy:
 stage: deploy
 artifacts:
  paths:
   - documentPreview.tar.gz
  
clean:
 stage: clean
 script:
  - php psh.phar clear
  