after_script:
 - php psh.phar clear

stages:
 - build
 - test

build:
 stage: build
  cache:
   untracked: true
 script:
  - php psh.phar build

test:
 stage: test
 cache:
  untracked: true
 script:
  - php psh.phar test