image: dockerregistry.metaways.net/tine20/documentpreview/build

stages:
 - test

test_branch:
 stage: test
 only:
  - branches
 script:
  - chmod +x composer.phar 
  - ./composer.phar install
  - ./vendor/phpunit/phpunit/phpunit