image: dockerregistry.metaways.net/tine20/documentpreview/build

stages:
 - test
 - build_and_deploy

test:
 stage: test
 script:
  - php psh.phar git:test

deploy_to_repo:
 stage: build_and_deploy
 only:
  - master
 script:
  - php psh.phar git-branches:build
  - php psh.phar git-branches:deploytorepo

