stages:
 - build
 - test
 - deploy
 
cache:
 key: "buildFolder$CI_COMMIT_SHA"
 paths:
  - build
  - "documentPreview-$CI_COMMIT_REF_NAME.tar.gz"
  - "documentPreviewService$CI_PIPELINE_ID.deb"
 
build:
 stage: build
 script:
  - php psh.phar build

test:
 stage: test
 script:
  - php psh.phar test
  
deploy:
 stage: deploy
 artifacts:
  paths:
   - "documentPreview-$CI_COMMIT_REF_NAME.tar.gz"
   - "documentPreviewService$CI_PIPELINE_ID.deb"
 script:
 - echo "this job is not empty"
 - php psh.phar deploy