before_script:
 - wget https://shopwarelabs.github.io/psh/psh.phar

after_script:
 - php psh.phar clear

stages:
 - build
 - test

build:
 stage: build
 script:
  - php psh.phar build

test:
 stage: test
 script:
  - php psh.phar build
  - php psh.phar test