paths: []
const: []
dynamic:
  VERSION_N_MM: echo $(php composer.phar show --self | sed '4q;d' | cut -c 14-)
  VERSION_N_MMP: echo $(php composer.phar show --self | sed '4q;d' | cut -c 14-).$CI_PIPELINE_ID
  REF_NAME: echo $CI_COMMIT_REF_NAME
  PROJECT_URL: echo $CI_PROJECT_URL
environments:
  git:
    paths:
     - buildscripts/regu
    const: []
    dynamic: []
  git-tags:
    paths:
     - buildscripts/spec
    const: []
    dynamic:
      VERSION_T: echo $CI_COMMIT_REF_NAME.$CI_PIPELINE_ID
      VERSION_PATH: echo $CI_PIPELINE_ID
  git-branches:
    paths:
     - buildscripts/spec
    const: []
    dynamic:
      VERSION_T: echo "2.0"$CI_COMMIT_REF_NAME #$(composer show --self | sed '4q;d' | cut -c 14-).$CI_PIPELINE_ID
      VERSION_PATH: echo "2.0"/$CI_PIPELINE_ID #$(composer show --self | sed '4q;d' | cut -c 14-)/$CI_PIPELINE_ID