---
- hosts:
    - default
  become: true
  become_user: root

  vars:
    - gitlab_runner_list:
      - description: documentPreviewRunner
        url: https://gitlab.metaways.net/
        executor: shell
        registration-token: 9FH5Jz7AHqQDwyBz4ECv


  pre_tasks:
    - include: ../../pre_tasks/remove_apt_entries.yml

    - name: execute apt-get update
      apt: update_cache=yes
      ignore_errors: yes

  tasks:
    - name: install requirements
      apt:
        name={{item}}
        state=present
      with_items:
        - graphicsmagick
        - ghostscript
        - unzip

        - libreoffice

    - name: add php7 ppa
      apt_repository:
        repo='ppa:ondrej/php'
        update_cache=yes
        state=present

    - name: install php7.2 packages
      apt:
        name={{item}}
        state=present
      with_items:
        - php7.2
        - php7.2-cli
        - php7.2-xml
        - php7.2-mbstring
        - php7.2-curl

    - name: set gitlab as known_host
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: gitlab.metaways.net
        key: "gitlab.metaways.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC30xRGIZDfd30he5LNtZOqi29FpL3Qlcbsxc6amUc2Z6isZT91Z+lCSKo/CV/qV+hH8SXCZDVdWaQhRVkOcRuV0RvtUzqe6MoNzpvgU8gWBlozzXSHSZo6r7RQmjQ0N1pKdjpvyKO4O6G9TB2F20Q4iVVDwirrGsbBjZGWXS4HWvS+4ksfNp4gEpcGsqUwjbHunMSrNVxrxEICWQepa9zVqUsx8mscd4WpYlVseJlaJyz/KBFSUDAAr3xIVBuhZhpQ0pvyEzh2dlv/OQyehznhWERDvgQIKnrykUkBMSCjgkE+p1/Hnz2S6uR12AbjAc/QmzE0qkFbOPplq6/5j4gE/P5i5Euzd7MW1XdEeIS8tyqQC912SrzOzm45uy3OV36p5we7IFM6kHJD5El0+7X82T9VXER1Wb6q3zBWCB+1cOCoY+OkEtJmooYGjuu7Beawav7vHsZX01ebMm+phzMDsuhEXsk363eW2Mja5triSdRIW4o36LXw3NNmDRI5+5WIMhBsHAppnekmc59OByk33zDErdLn3AsIl67XqyzCxTAiP8iUVAW6z0j9KCyDSRkTIkDWhbiN2Cielz3muTIuZyV48hV4JoLKZ4S7wE1llu8RcBHLOgw+6yfUOFAYVxFgBOucSylrfxdS3pXWN06Br+kGVmQIc+SCrFvmm6yPpw=="

    - name: generate ssh keys
      user:
        name: gitlab-runner
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - fetch:
        src: /home/gitlab-runner/.ssh/id_rsa.pub
        dest: ../../pub_keys

  roles:
    - solval.gitlab_runner