version: '2'
services:
        document-preview:
                image: document-preview:latest
                container_name: document-preview
                volumes:
                        - ../:/document-preview/document-preview:ro
                        - ./configs/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro
                        - ./configs/sample_config.php:/etc/documentPreviewService/VERSION/config.php:ro
                
                ports:
                        - "80:5000"
                environment:
                        PHP_IDE_CONFIG: "serverName=documentPreview"
                        #XDEBUG_CONFIG: "remote_host=192.168.33.1 remote_enable=on remote_port=9000"

