version: '2'
services:
  document-preview:
    image: document-preview:latest
    build:
      context: .
    container_name: document-preview
    volumes:
      - ../:/document-preview/document-preview:ro
      - ./configs/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro
      - ./configs/sample_config.php:/etc/documentPreviewService/VERSION/config.php:ro

    ports:
      - "5000:80"
    environment:
      PHP_IDE_CONFIG: "serverName=documentPreview"
      XDEBUG_CONFIG: "remote_host=172.118.0.1 remote_enable=on remote_port=9001"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.118.0.0/16
